#-------------------------------
# General Site Settings
baseURL = "http://example.org/"
languageCode = "en-us"
title = "Joseph Lawrence"
googleAnalytics = "" # Add your identifier. For example UA-99631805-1.
paginate = 5


#-------------------------------
# Main Menu
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 2

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact"
    weight = 3

  [[menu.main]]
    identifier = "elements"
    name = "Elements"
    url = "/elements"
    weight = 4


[params]
  logo = "" # You can add own logo. For example "/images/logo.png".
  description = "Joseph is a super minimal content focus theme for Hugo."

  [params.author]
    name = "Joseph Lawrence"
    bio = "I'm a designer & products creator. I teach designers code and developers design. Passionate about people, health, & design systems."
    avatar = "/images/01.jpg"

  #-------------------------------
  # Hero Settings
  [params.hero]
    hero__title = "Hey, I’m Joseph! Designer & Developer."
    hero__description = "I'm a designer & products creator. I teach designers code and developers design. Passionate about people, health, & design systems."
    hero__image = "/images/01.jpg"

  [[params.social]]
    icon = "ion-logo-twitter"
    name = "Twitter"
    link = "https://twitter.com"

  [[params.social]]
    icon = "ion-logo-facebook"
    name = "Facebook"
    link = "https://facebook.com"

  [[params.social]]
    icon = "ion-logo-pinterest"
    name = "Pinterest"
    link = "https://pinterest.com"

  [[params.social]]
    icon = "ion-logo-dribbble"
    name = "Dribbble"
    link = "https://dribbble.com"

  [[params.social]]
    icon = "ion-logo-instagram"
    name = "Instagram"
    link = "https://instagram.com"

  [[params.social]]
    icon = "ion-logo-vimeo"
    name = "Vimeo"
    link = "https://vimeo.com"

  # Example of adding a new link to the author section and footer:
  # [[params.social]]
  #   icon = "ion-logo-github"
  #   name = "Github"
  #   link = "https://github.com/gohugoio"

  # Other icons can be found at https://ionicons.com/v4/

  #-------------------------------
  # Newsletter (partials/footer-widgets/widget-subscribe.html)
  [params.mailchimp]
    mailchimp__title = "Get interesting news"
    mailchimp__text = "Subscribe to our newsletter and we’ll send you the emails of latest posts."
    mailchimp__identifier = "" # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
    mailchimp__button__text = "Join" # Add your button text

  #-------------------------------
  # Contact Settings
  [params.contact]
    email = "your@email.com" # Add your form_id

    # NOTE
    # Joseph comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.

  #-------------------------------
  # Comment Section (Disqus)
  [params.disqus]
    disqusShortname = "anvodstudio-joseph" # add your shortname for Disqus Comment. For example anvodstudio-joseph


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[outputs]
  home = ["HTML", "RSS", "JSON"]


[markup.highlight]
  codeFences = true
  guessSyntax = true
  noClasses = false